name: Elemeno Build Elyra Docker
on:
  push: # all branches

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Build elyra python server
        run: |
          pip install -r etc/docker/elyra/requirements.txt
          make build-server
      - name: prepare dirs
        env:
          TAG: 3.12.0
          ELYRA_VERSION: 3.12.0
        run: |
          mkdir -p build/docker
          cp etc/docker/elyra/Dockerfile build/docker/Dockerfile
          cp etc/docker/elyra/start-elyra.sh build/docker/start-elyra.sh
          cp etc/docker/elyra/requirements.txt build/docker/requirements.txt
          mkdir -p build/docker/elyra
          cp dist/elyra-${{ env.ELYRA_VERSION }}-py3-none-any.whl build/docker/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build docker
        uses: docker/build-push-action@v2
        with:
          build-args: |
            ELYRA_VERSION=${{ env.ELYRA_VERSION }}
            TAG=${{ env.TAG }}
          file: etc/docker/elyra/Dockerfile
          context: etc/docker/elyra
          tags: 361265061473.dkr.ecr.us-east-1.amazonaws.com/elemeno-elyra:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Push docker
        if: ${{ contains(github.ref_name, 'RELEASE') }}
        uses: docker/build-push-action@v2
        with:
          build-args: |
            ELYRA_VERSION=${{ env.ELYRA_VERSION }}
            TAG=${{ env.TAG }}
          file: etc/docker/elyra/Dockerfile
          context: etc/docker/elyra
          push: true
          tags: 361265061473.dkr.ecr.us-east-1.amazonaws.com/elemeno-elyra:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max